tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "shivammathur/php"
brew "cocoapods"
brew "php", restart_service: true
brew "composer"
brew "php@7.4"
brew "python@3.10"
brew "watchman"
brew "shivammathur/php/php"
cask "dbeaver-community"
cask "iterm2"
